#!/bin/sh /usr/share/dpatch/dpatch-run
## 01-manpage.dpatch by Marvin Stark <marv@der-marv.de>
##
## DP: Fix manpage character error.

@DPATCH@

Index: mini-httpd-1.21/mini_httpd.8
===================================================================
--- mini-httpd-1.21.orig/mini_httpd.8
+++ mini-httpd-1.21/mini_httpd.8
@@ -432,7 +432,7 @@ You don't need cert.csr and privkey.pem,
 .SH "SEE ALSO"
 htpasswd(1), weblog_parse(1), http_get(1)
 .SH AUTHOR
-Copyright © 1999,2000 by Jef Poskanzer <jef@mail.acme.com>. All rights reserved.
+Copyright \[co] 1999,2000 by Jef Poskanzer <jef\[at]mail.acme.com>. All rights reserved.
 .\" Redistribution and use in source and binary forms, with or without
 .\" modification, are permitted provided that the following conditions
 .\" are met:
