#!/bin/bash

sed -i -e '/^@LONGNAME@/d' /etc/issue

OVERRIDEDIR=/etc/insserv/overrides
for OVERRIDE in ssh snmpd; do
	grep -q zenloadbalancer $OVERRIDEDIR/$OVERRIDE >/dev/null 2>&1 && rm $OVERRIDEDIR/$OVERRIDE
	update-rc.d $OVERRIDE defaults
done

update-rc.d -f zenloadbalancer remove

invoke-rc.d zenloadbalancer stop
/etc/init.d/minihttpd stop

exit 0
