#!/bin/sh -e
V=1.27
D=mini_httpd-$V
P=mini_httpd_patches
TAR=mini_httpd-${V}.tar.gz
TARLOC=http://www.acme.com/software/mini_httpd/$TAR
CONFLICT="mini-httpd-debug"
KEEPDIR=0
PKGNAME=mini-httpd
DEBUG=0
DEBUGFLAGS=""

while [ "x$1" != "x" ]; do
	if [ "x$1" = "x-k" ]; then
		KEEPDIR=1
		shift
		continue
	fi
	if [ "x$1" = "x-d" ]; then
		DEBUG=1
		DEBUGFLAGS="--strip=no"
		PKGNAME=mini-httpd-debug
		CONFLICT="mini-httpd"
		shift
		continue
	fi
	echo "usage : make_minihttpd [-k] [-d]"
	exit 2
done

rm -rf $D
if [ ! -f $TAR ]; then
	wget $TARLOC
fi

tar xfz $TAR
find $D -exec chmod u+w \{\} \;

p() {
	echo "Patch: $2"
	patch -d $D -p1 < $P/$2
}

p $D 01-manpage
p $D fix-change-index-document-root
p $D 03-cgi-php
p $D 04-kfreebsd.dpatch
p $D fix-port
p $D 05-manpage-hyphen
p $D fix-append-portno-to-vhost
p $D fix-makefile
p $D enable-ssl
p $D fix-includes
p $D fix-noise
p $D fix-overread
if [ $DEBUG -ne 0 ]; then
	sed -i -e '/^CFLAGS/s/-O/-g/' -e '/^LDFLAGS/s/-s //' \
		-e 's/`dpkg-buildflags[^`]*`//g' $D/Makefile
	sed -i -e 's/^#define READ_TIMEOUT.*/#define READ_TIMEOUT 900/' \
		-e 's/^#define WRITE_TIMEOUT.*/#define WRITE_TIMEOUT 900/' \
		$D/mini_httpd.c
	sed -i -e '/"port.h"/a\
#undef HAVE_SENDFILE\
#undef HAVE_LINUX_SENDFILE' $D/mini_httpd.c
fi
echo "done"
( cd $D
make
export SUMMARY="small, simple http daemon, supports SSL"
fakeroot checkinstall --pkgname $PKGNAME -D $DEBUGFLAGS --maintainer "Steve\ Goldthorpe\ \<steve@karmalb.org.uk\>" --requires libssl1.0.0 --reset-uids --install=no --pkgsource="http://www.acme.com/software/$TAR" --pkggroup=web --pkglicense="BSD-2-clause" --provides "httpd, httpd-cgi" --conflicts "apache2-utils,$CONFLICT" -y --pakdir=.. --deldoc
)

test $KEEPDIR -eq 1 || rm -rf $D
